const disposableDomains = new Set([
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '20minutemail.com', '33mail.com', '4jmail.gq', 'abcmail.email',
  'adguardmail.com', 'anon-mail.com', 'anonymail.info', 'anonymail.io',
  'anondomain.stream', 'atmpipi.com', 'bakinmail.com', 'bastard.lol',
  'beeroot.co.uk', 'bemail.org', 'bevia.net', 'bigstring.com',
  'blackbearmail.com', 'blackbirdmail.com', 'bobmail.info', 'boftjunk.com',
  'bombita.com', 'card.zone', 'casualmail.com', 'challien.email',
  'chibuki.cf', 'chongclouded.club', 'chongemail.fun', 'ciubi.com',
  'clay.gl', 'clrmail.com', 'cmail.com', 'cmail18.com', 'cmail2u.com',
  'cobra-mail.com', 'correo-blog.tk', 'corriere.net', 'coupdude.com',
  'cow.cx', 'cpa.cc', 'crate.ro', 'crated.press', 'creasemail.com',
  'cryfor.me', 'ctos.gifts', 'ctox.cf', 'cu.cc', 'currycity.co.uk',
  'cyberbyte.net', 'cyberservices.com', 'cyboxmail.com', 'dada.pl',
  'damail.se', 'dandy-id.net', 'dark.party', 'darkmail.site',
  'degoo.com', 'deliriums.info', 'demimonde.com', 'despam.io',
  'despamix.com', 'dev-null.xyz', 'digitales.tv', 'digitoy.org',
  'digiseed.org', 'diigo.com', 'dm.kepsi.uk', 'dodgygig.com',
  'doki-2000.com', 'dokioe.com', 'dontsend.me', 'dotmsg.org',
  'drdrb.net', 'dropcradle.net', 'dumpemail.com', 'dumpyemail.com',
  'dwindss.com', 'dyemoox987.ga', 'dynamx.io', 'e4ward.com',
  'earthlink.net', 'easy-mail.ml', 'edsd2016.com', 'eee-mail.com',
  'elektronicamente.com', 'email-fake.com', 'emailfake.com',
  'emailias.com', 'emailshell.com', 'emailspam247.com', 'emailure.net',
  'embarqmail.com', 'example.com', 'example.net', 'example.org',
  'exemail.com.au', 'explodemail.com', 'fakeinbox.com', 'fakeinformation.com',
  'fanshopmail.com', 'fantasmmail.com', 'faxal.co', 'felicity-h.com',
  'fermemail.com', 'ferramentas.co', 'filenofer.com', 'flixos.cc',
  'flowapp.net', 'fmail.co', 'fmail.gp', 'forevermail.com',
  'freeglob.com', 'freetardis.net', 'fug.com', 'fugged.com',
  'fyemail.com', 'garbagemail.com', 'gaymail.com', 'geckoboard.com',
  'geckomail.com', 'get2mail.com', 'getalocket.com', 'getmeek.com',
  'ghostmail.com', 'gighu.org', 'girlsodigital.co', 'gix.it',
  'glacialfleece.com', 'glao-sekr.com', 'glayy.org', 'gleeze.com',
  'glitch.email', 'globe.gov', 'globo.com', 'gmial.com',
  'goacashturf.com', 'goo-mail.com', 'goldmail.net', 'goldposmail.com',
  'golfemail.com', 'gosmilly.com', 'got-2.net', 'goworkmail.com',
  'gr8name.komatsu', 'grr.la', 'gsrv.net', 'guerrillamail.com',
  'guerrillamailblockrcas.com', 'guerrillamaildesi.com', 'guerrillamet.com',
  'h.mailsurf.cyou', 'h8h.com', 'haird20.com', 'hawkemail.net',
  'hacked.to', 'haltospam.com', 'hapiinsocial.com', 'hardcorefacts.com',
  'hastey.io', 'haters.dies', 'headfulofhorrors.com', 'heapmail.com',
  'highsecuritytest.com', 'hmailo.com', 'hochstaffl.eu', 'hodgsonline.eu',
  'honor.es', 'hope.dinnerud.no', 'hotmal.com', 'hotmial.com',
  'hotmail.co.uk', 'hotmail.de', 'hotmail.fr', 'hotmail.net', 'hotmail.org',
  'hotmailc.com', 'hotmailc.net', 'hotmailcheap.net', 'hotmailcl.com',
  'hotmaiwl.com', 'hotmmail.com', 'hotmoal.com', 'hotmopost.com',
  'howlo.net', 'hush.com', 'hush.ai', 'hushmail.com', 'hushmail.me',
  'husteax.com', 'i.crazyhitty.ch', 'i.ua', 'iamawesome.com',
  'iamwatchingyou.info', 'icon.co.za', 'icxexchange.com', 'idby.me',
  'ieee.org', 'illistei.com', 'imails.info', 'imapmail.org',
  'imcmail.com', 'imgay.com', 'imgay2000.com', 'imgmp.com',
  'imstupide.com', 'inappur.com', 'inbox.com', 'inbox.lv', 'inbox.nu',
  'inbox7.com', 'inbox89.com', 'internet-clients.com',
  'international-dev.com', 'interoutepvtl.com', 'interwebz.tech',
  'intopulo.com', 'invermin.com', 'irishbbq.com', 'iroidz.com',
  'irony.org', 'iservefarm.com', 'islandemail.info', 'istakal.com',
  'itdad.komatsu', 'itga.life', 'itspan.tk', 'ivimos.com', 'jable.name',
  'japn.com', 'jerk.com', 'jewbojunk.com', 'jipx.com', 'jmailb.com',
  'joojoo.info', 'joseonedwards.com', 'junkmail.com', 'junkmail.de',
  'jupimo.com', 'just4fun24.live', 'kaemail.com', 'kamikazemail.com',
  'kayak.com', 'kbox.expired.one', 'kbox.risky.one', 'kek.net',
  'kerrxp.com', 'ketik.sucks', 'khoobus.info', 'killermail.com',
  'killmail.com', 'kimo.com', 'kink.com', 'kinzo0999.com',
  'kiratohero53.su', 'kitp0.com', 'kkj.tk', 'klud.de', 'klunky.com',
  'kmno.com', 'knol.com', 'kommunist.org', 'kpj3.net',
  'kpopfanjournal.email', 'krakenmail.com', 'kruca.email', 'krwml.com',
  'labs253.com', 'lajoconde.net', 'lastmail.guru', 'lastmsg.com',
  'leapbridemail.com', 'leech.org', 'leemail.com', 'lemmon.me',
  'leosj.com', 'letimago.com', 'lgpf.net', 'lilengineers.com',
  'limeremail.com', 'lindenwe.com', 'linked-int.com', 'link2mail.com',
  'lipson.org', 'listomail.info', 'liverpoolcitydirect.org',
  'loandkimo.com', 'lol.831c.com', 'lolmail.co', 'lolmail.in',
  'loveric.com', 'luv2die.com', 'lycos.com', 'lycos.asia',
  'lycos.co', 'lycos.co.uk', 'mac.com', 'mail-force.com', 'mail-game.com',
  'mail.com', 'mail11.com', 'mail1a.com', 'mail2000.com',
  'mail333.com', 'mail4i.net', 'mail4u.info', 'mailback.com',
  'mailinator.com', 'mailinator.net', 'mailinator.org',
  'mailinator2.com', 'mailinator2000.com', 'mailinator3.com',
  'mailinator777.com', 'mailinator888.com', 'mailinator999.com',
  'mailinacup.com', 'mailismagic.com', 'maility.com', 'mailexpire.com',
  'mailfaux.com', 'mailfreedom.club', 'mailguard.info', 'mailhero.net',
  'maili.info', 'mailincubator.com', 'mailinatorhost.com',
  'mailinatorworld.com', 'mailinatorhub.com', 'mailinatorfuture.com',
  'mailinator399.com', 'mailinator489.com', 'mailinator500.com',
  'mailinator578.com', 'mailinator590.com', 'mailinator620.com',
  'mailinator653.com', 'mailinator678.com', 'mailinator729.com',
  'mailinator844.com', 'mailinator850.com', 'mailinator862.com',
  'mailinator998.com', 'mailinator906.com', 'mailinator921.com',
  'mailinator937.com', 'mailinator948.com', 'mailinator960.com',
  'mailinator962.com', 'mailinator984.com', 'mailinator992.com',
  'mailinator996.com', 'mailinator997.com', 'mailinator.com',
  'mailinator2020.com', 'mailinator2021.com', 'mailinator2022.com',
  'mailinator2023.com', 'mailinator2024.com', 'mailinator2025.com',
  'mailinator2026.com', 'mailinatorfuture.com',
  'mailo.com', 'mailo24.com', 'mailo55.com', 'mailoc.com',
  'maildrop.cc', 'maildrop.cf', 'maildrop.ga', 'maildrop.gq', 'maildrop.ml',
  'maildrop.tk', 'maildrop2.com', 'maildrop3.com', 'maildrop678.com',
  'maildropbox.com', 'maildropzone.com', 'maildroid.com',
  'mailexist.com', 'mailfavor.com', 'mailfly.com', 'mailgeek.com',
  'mailgen.com', 'mailguys.com', 'mailhole.net', 'mailhost.de',
  'mailhost101.com', 'mailhub.com', 'maillot.com', 'mailme.com',
  'mailme2.net', 'mailmeanywhere.com', 'mailmetrash.com', 'mailmia.com',
  'mailmints.com', 'mailmp3.com', 'mailmymail.com', 'mailnex.us',
  'mailnight.net', 'mailnull.com', 'mailonaut.com', 'mailorc.com',
  'mailothermail.com', 'mailpanda.com', 'mailpix.com', 'mailpriv.com',
  'mailproof.com', 'mailreply.com', 'mailrepromo.com', 'mailres.com',
  'mailroom.com', 'mailroom2.com', 'mailr.com', 'mailsentinel.com',
  'mailet.com', 'mailtome.de', 'mailtroll.com', 'mailv2.net',
  'mailvenue.com', 'mailviz.com', 'mailwatcher.com', 'mailwatchers.com',
  'mailwork.com', 'mailx.com', 'mailxu.com', 'maim.in',
  'maine-craigslist.org', 'mammamail.com', 'manybrain.com', 'me.com',
  'me59.com', 'meltmail.com', 'mesmtp.com', 'messaging.fyi',
  'metadrop.org', 'mintemail.com', 'mnshirt.com', 'mnsndr.com', 'mozzi.net',
  'msg.app', 'msgedr.com', 'msgtm.com', 'mspec.photography',
  'mtn.co.zm', 'mtveri.net', 'muc.de', 'multimania.org',
  'mymail-in.net', 'mymail.ca', 'mymail.cloud', 'myspam.co',
  'myspam.de', 'myspammail.com', 'mytempemail.com', 'mytempmail.com',
  'mytravelpod.com', 'myjunkmail.com', 'nachoemail.com', 'namehero.net',
  'nastytown.in', 'neatbox.com', 'nerdmail.com', 'nmail364.neocities.org',
  'nomadmail.com', 'nomail.io', 'nonspam.eu', 'nonspambiz.com',
  'nonspam.am', 'normalbrain.net', 'nospam.ro', 'nospam4u41.com',
  'notspam.lol', 'nowhere.org', 'nowmail.onmicrosoft.com', 'nude.ninja',
  'nullified.ai', 'nullified.email', 'nym.hk', 'nymail.com', 'nyms.net',
  'oal.top', 'oddmail.io', 'odnorod.ru', 'onedrive.com',
  'onemailonly.net', 'one-time.email', 'onewayemail.com', 'onmail.eu',
  'openzimbra.com', 'orange.fr', 'orange.nl', 'origamail.com',
  'othersonar.com', 'ourkidsmail.com', 'outlook.com', 'outlook.in',
  'outlook.jp', 'overclockers.ua', 'oww.com', 'p33k.eu', 'p4ss.me',
  'page.plus', 'panthermail.com', 'pandora.be', 'parcelperform.net',
  'paramore.email', 'park-mail.com', 'passwordbox.com', 'pawxx.ml',
  'pdx001.net', 'pechkin.com', 'petalfish.com', 'pfdq.net',
  'phamily.com', 'phoneme.org', 'photomediocorp.com', 'phreak.nut.cc',
  'phreaker.net', 'phrygian.net', 'physio.rocks', 'pi.vu',
  'piazza.com', 'piedbits.com', 'pigeonmail.net', 'pigmail.com',
  'pills.com', 'pimple.net', 'pinbox.co', 'pingbe.net',
  'pinkguinea.com', 'pivots.com', 'pkwifil.com', 'plandiscout.com',
  'plasticcode.com', 'pleasedeleteme.com', 'plorkmail.com', 'pluckymail.com',
  'pointbluebox.com', 'poipw.com', 'pokemail.com', 'pokemongo.mom',
  'poofy.net', 'popeye8.com', 'popmail.com', 'popmail1.com',
  'pornovispa.org', 'posteo.net', 'pounced.pw', 'praktikantmail.com',
  'postonline.me', 'posterityllc.com', 'postpro22.com', 'powdermail.com',
  'pracmail.com', 'prank.email', 'prankasif.com', 'prankl.com', 'praz.org',
  'primails.com', 'primeface.com', 'pro-email.org', 'prodigygangster.com',
  'proinbox.com', 'promail322.com', 'protonmail.com',
  'protonmail.ch', 'prsd.camp', 'prtny.com', 'ps9a.com', 'psn.net',
  'pugliese.com', 'pugmail.com', 'pullthecurtain.com', 'puny.io',
  'pustystudio.com', 'put2office.com', 'putrid.com', 'qis.io',
  'qppt.com', 'qxf.io', 'qy.fi', 'qwerty.org', 'r0h.us', 'r-mail.ml',
  'railo8.com', 'rambler.com', 'randomail.com', 'rapmailto.com',
  'rapidpigs.com', 'rappmail.com', 'raskrutka.org', 'reality-concept.com',
  'reallymy.email', 'recode.me', 'recreateme.tk', 'recursor.net',
  'redwhitecoupon.com', 'reefwalker.com', 'reply.io', 'reptil.io',
  'resend.com', 'resends.net', 'retepmosh.com', 'retnegofleek.com',
  'revolvingdoorhater.com', 'rfaclient.com', 'rhyta.com', 'rigcel.com',
  'rigfiles.net', 'ringto.net', 'riotcat.net', 'rm1-once.today',
  'rpost.it', 'rtk.net', 'rtrtr.com', 'rump.com', 'runupi.com',
  'ruq.in', 'rychost.com', 'rychost.net', 'safe-mail.net',
  'safetymailspace.com', 'salmonemail.com', 'sandwen.com', 'sanitized.net',
  'says.cx', 'sbif.se', 'scicomalo.com', 'seby.io', 'seconde.space',
  'secretbox.nl', 'secmail.gq', 'secmail.pro', 'selloi.com',
  'send4up.org', 'sendanon.com', 'sendemaily.com', 'sendflood.com',
  'sendlater.com', 'sendnow.live', 'sendspam.email', 'sensical.link',
  'sensory.com', 'seriousmail.com', 'sesmoverdo.com', 'sexy-rss.com',
  'sexykate.com', 'sf-f.net', 'shagbag.com', 'shaman.com',
  'shandalen.com', 'shavedgirls.info', 'shredmail.com', 'sibmail.com',
  'simaland.net', 'simplemail.info', 'skahwah.com', 'skmail.me',
  'skull.ml', 'sll.sk', 'smaaktijd.com', 'smbiztime.email',
  'smehosting.me', 'smart-mail.com', 'snakemail.com', 'spam-block.com',
  'spam.felixbohn.de', 'spamgourmet.com', 'spankthegoat.com',
  'spermmail.com', 'spider.net', 'spoofmail.ml', 'squoosh.email',
  'ss.com', 'stankdick.net', 'starkmail.com', 'stinju.com',
  'stop-spoofing.com', 'stp-works.com', 'streamsquid.com',
  'street-chemistry.com', 'streetmail.com', 'successfultips24.com',
  'superrito.com', 'superwebmail.com', 'superworm.com',
  'surrenderyourpassword.com', 'sussed.org', 'spambog.com',
  'spambog.de', 'spambog.net', 'spambog.ru', 'spambog.org',
  'spambog.biz', 'spambog.info', 'spambog.name', 'taglet.org',
  'taisies.com', 'talkinator.com', 'talktalking.net', 'tagmail.com',
  'talktome.org', 'tanami.com', 'targettr.com', 'task.gfamily.org',
  'temp-mail.com', 'temp-mail.org', 'temp-mail.net', 'temp-mail.top',
  'temp-mail.ml', 'temp-mail.ga', 'temp-mail.cf',
  'tempinbox.com', 'tempmail.com', 'tempmail.co', 'tempmail.de',
  'tempmail.net', 'tempmail.org', 'tempmail.pt', 'temp-mail.ru',
  'temporaryemail.com', 'temporary-email.com', 'tempr.email',
  'terr.co', 'terranplanet.net', 'testie.ai', 'testmail.app',
  'the3000.com', 'thejacksonunion.org', 'thelimedrawer.com',
  'themall.io', 'theoutsourcing.com', 'thepiratebeach.net',
  'thepirateplanet.net', 'therealloot.com', 'theskepticalme.com',
  'thestoryist.com', 'thewastedgeneration.com', 'thewpo.com',
  'thinktank.com', 'thisisnotmyrealemail.com', 'timewarp.be',
  'tmail.com', 'tmail.io', 'tmail.ly', 'tmailbox.co',
  'tmailinator.com', 'todayhost.net', 'tooncastthenews.com',
  'toolsbay.info', 'toreadit.com', 'tortomise.com', 'totalcore.org',
  'towana.kr', 'tpg.com.au', 'trace.lol', 'tradermail.org',
  'trbvm.com', 'trash2011cologne.de', 'trashmail.com', 'trashmail.de',
  'trashmail.ga', 'trashmail.holdings', 'trashmail.info', 'trashmail.net',
  'trashmail.org', 'trash-me.com', 'tripop.net', 'tubequeen.com',
  'turual.com', 'tusentakter.com', 'tvland.com', 'tvnomail.com',
  'typepage.net', 'tyop1.com', 'uluturka.com', 'uplift.id', 'uymail.com',
  'valemail.me', 'vampirefreaks.com', 'vbandaids.com', 'vdnbell.net',
  'vembian.com', 'veritable.com', 'vgx.me', 'viacard.top', 'vidchart.com',
  'vidict.net', 'vigilante.de', 'vidoop.com', 'vinternet.com',
  'visa.com', 'visamail.info', 'visipoor.com', 'visterkoeot.com',
  'vmails.info', 'volofootball.com', 'vomoto.com', 'vote2020.email',
  'vpsiz.com', 'vpsmail.net', 'vtext.com', 'vtruckmobile.com',
  'vupmailbox.com', 'vyozvy.com', 'walalla.info', 'wasteland.rackhero.com',
  'wcrtec.com', 'web.email', 'webaddress.org', 'webaudean.com',
  'webcammail.com', 'webcompute.io', 'webdo.com', 'webdon.com',
  'webhero.net', 'webidle.com', 'webmail.cow', 'webmail.com',
  'webmail.com.au', 'webmail.de', 'webmail.fr', 'webmail.org',
  'webmail.ru', 'webmail2.com', 'webmail4u.com', 'webmails.com',
  'webmailserver.net', 'webninja.com', 'weboz.co', 'websters.com',
  'webtech7.com', 'webtechs.com', 'webtools.co', 'webtribe.org',
  'weez.com', 'weirdness.in', 'wetrainbay.com', 'wh4t.org',
  'whashost.com', 'whatthe.net', 'whizdata.com', 'whoops.net',
  'widdlewabbit.com', 'wilsonify.com', 'winfree.com', 'winnipegfreepress.com',
  'winop.com', 'wintastic.net', 'wintervoice.com', 'wirefriends.com',
  'wishlistemail.com', 'witohi.net', 'wokcity.nl', 'wolfox.com',
  'wongfunk.com', 'woohoo.com', 'wow.com', 'writeme.com',
  'writemeback.com', 'wrong.cf', 'wubben.com', 'wupics.com',
  'wyrmzone.net', 'x2mail.com', 'xemaps.com', 'xmail.com',
  'xmaily.org', 'xoxy.com', 'xspeeder.com', 'xtra.co.nz',
  'xtrafluff.com', 'xxi2.com', 'y2kid.com', 'y2mail.com',
  'yadro.com', 'yandex.com', 'yandex.ru', 'yatho.com', 'yemai.com',
  'yep.it', 'yfrog.com', 'yhdmail.com', 'ymail.com', 'yoa.com',
  'yola.com', 'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yopmail.org',
  'yopmail.in', 'yopmail.cc', 'yopmail.golden3.com',
  'yopmail.golden4.com', 'yopmail.golden5.com',
  'your-freedom.net', 'your-mail.com', 'your-mailbox.com', 'youremail.org',
  'yours.com', 'yourtrash.co', 'ytnest.com', 'yuckemail.com',
  'z0d99.com', 'z1p.de', 'zaach.com', 'zamzile.com',
  'zbxb.com', 'zbox.com', 'zecco.com', 'zemail.com',
  'zetmail.com', 'zidz.com', 'zilladickinson.com', 'zionfarm.com',
  'zonatelera.com', 'zonk.net', 'zone-x.com', 'zope.com',
  'zor.nu', 'zoul.com', 'zoznam.sk', 'zrxflame.io',
  'zshare.de', 'ztest.zleht.net', 'zumbox.com', 'zut.to',
  'zvents.com', 'zweb.org', 'zxq.com', 'zybermail.com', 'zyrd.com', 'zyzi.com'
]);

export function isDisposableEmail(email) {
  if (!email || !email.includes('@')) return false;
  const domain = email.split('@')[1].toLowerCase();
  return disposableDomains.has(domain);
}

export default isDisposableEmail;
