#!/usr/bin/env node
/**
 * Agent B — cleanup script for API-test artifacts.
 *
 * Deletes ONLY rows generated by server/tests/*:
 *   users → email starts with "agb." and ends with "@example.com"
 *   rooms → name starts with "agentb-"   (messages cascade-delete)
 * Deleting users also cascades their sessions. Audit-log rows are kept
 * on purpose (userId becomes NULL via onDelete: SetNull) to preserve history.
 *
 * Usage:
 *   node --env-file=.env tests/cleanup.js            # dry run (default)
 *   node --env-file=.env tests/cleanup.js --apply    # actually delete
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({ log: ['error'] });
const apply = process.argv.includes('--apply');

const userFilter = { email: { startsWith: 'agb.', endsWith: '@example.com' } };
const roomFilter = { name: { startsWith: 'agentb-' } };

try {
  const [users, rooms] = await Promise.all([
    prisma.user.count({ where: userFilter }),
    prisma.room.count({ where: roomFilter })
  ]);

  console.log(`Found ${users} test user(s) and ${rooms} test room(s).`);

  if (!apply) {
    console.log('Dry run — re-run with --apply to delete.');
    process.exit(0);
  }

  // Rooms first (messages cascade), then users (sessions cascade).
  const deletedRooms = await prisma.room.deleteMany({ where: roomFilter });
  const deletedUsers = await prisma.user.deleteMany({ where: userFilter });

  console.log(`Deleted ${deletedRooms.count} room(s) and ${deletedUsers.count} user(s).`);
} catch (err) {
  console.error('Cleanup failed:', err.message);
  process.exitCode = 1;
} finally {
  await prisma.$disconnect();
}